name: Build and Release Todo App

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g., v1.0.0)"
        required: true
        default: "v1.0.0"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: mingw-w64-x86_64-gcc

      - name: Build executable
        shell: msys2 {0}
        run: gcc -I include -o todo.exe src/main.c src/storage.c src/task.c src/utils.c -mwindows -lcomctl32

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: todo-exe
          path: todo.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: todo-exe
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ github.token }}
          files: dist/todo.exe
          tag_name: ${{ github.event.inputs.version || github.ref_name }}
          name: Release ${{ github.event.inputs.version || github.ref_name }}
          generate_release_notes: true
